"""
utils/exporter.py
─────────────────
Generates premium PDF executive briefings from the AI analysis.
"""

from fpdf import FPDF
import datetime
import os

class ExecutiveBrief(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'DocuMind AI // Executive Briefing', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")} | Page ' + str(self.page_no()), 0, 0, 'C')

def create_pdf_report(content: str, filename: str = "executive_brief.pdf") -> str:
    pdf = ExecutiveBrief()
    pdf.add_page()
    
    # Title Section
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(37, 99, 235) # Primary Blue
    pdf.cell(0, 20, "Intelligence Summary", 0, 1, 'L')
    pdf.ln(5)
    
    # Content body
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(30, 41, 59) # Text Dark
    
    # Replace characters that FPDF might struggle with
    clean_content = content.replace('**', '').replace('*', '').replace('`', '')
    
    pdf.multi_cell(0, 10, clean_content)
    
    # Disclaimer
    pdf.ln(20)
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100, 116, 139) # Text Light
    pdf.multi_cell(0, 8, "Disclaimer: This briefing was autonomously generated by the DocuMind Multi-Agent System. Please verify critical facts against the original source documents cited in the interactive session.")
    
    output_path = os.path.join("uploads", filename)
    os.makedirs("uploads", exist_ok=True)
    pdf.output(output_path)
    return output_path
